name: Continuous Integration

on: push

jobs:
  check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['6']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install requirements
        run: |
          yarn install

      - name: Run tests
        run: |
          yarn ci

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
